### ISSUE TITLE
Release missing hash for arm64

### ISSUE THREAD

**Issue by tdschwarz** [hightouchio/cli#1]
I had to modify the download_and_verify function in the script to install ht CLI on an m1 macbook because there is no arm64 hash available for the install script to download.

### Lines causing the issue:
https://github.com/hightouchio/cli/blob/c9efb8fb96da1c50447494df747f25743459f138/install.sh#L124-L129
https://github.com/hightouchio/cli/blob/c9efb8fb96da1c50447494df747f25743459f138/install.sh#L74-L79
### Error message:
`[INFO]  Finding latest release`
`[INFO]  Using v0.1.0 as release`
`[INFO]  Downloading hash https://github.com/hightouchio/cli/releases/download/v0.1.0/sha256sum-arm64.txt`
`[ERROR]  Hash download failed`
### Function I had to modify:
https://github.com/hightouchio/cli/blob/c9efb8fb96da1c50447494df747f25743459f138/install.sh#L177-L192

**Comment by StrongMonkey** [comment]
Should be fixed by latest install script. Feel free to reopen if you are still seeing issues.
